/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.panels;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author PC
 */
public class CatalogosPanel extends javax.swing.JPanel {

    /**
     * Creates new form CatalogosPanel
     */
    public static CatalogosPanel instance;
    public CatalogosPanel() {
        initComponents();
        instance=this;
        showPanel(new MarcasPanel());
    }
    public void showPanel(JPanel panel) {
    panel.setSize(contentCatalogo.getWidth(), contentCatalogo.getHeight());
    panel.setLocation(0, 0);

    contentCatalogo.removeAll();
    contentCatalogo.setLayout(new BorderLayout());
    contentCatalogo.add(panel, BorderLayout.CENTER);

    contentCatalogo.revalidate();
    contentCatalogo.repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentCatalogo = new javax.swing.JPanel();

        contentCatalogo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentCatalogoLayout = new javax.swing.GroupLayout(contentCatalogo);
        contentCatalogo.setLayout(contentCatalogoLayout);
        contentCatalogoLayout.setHorizontalGroup(
            contentCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        contentCatalogoLayout.setVerticalGroup(
            contentCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentCatalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentCatalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentCatalogo;
    // End of variables declaration//GEN-END:variables
}
