/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views.panels;

import java.awt.Color;
import java.awt.Cursor;
import Views.panels.MarcasForm;


/**
 *
 * @author PC */
public class MarcasForm extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MarcasForm.class.getName());
    private boolean esEdicion = false;
    private String idMarcaOriginal = "";
    private MarcasPanel panelMarcas;
    /**
     * Creates new form ClientesForm
     */
    public MarcasForm(java.awt.Frame parent, boolean modal, MarcasPanel panel) {
        super(parent, modal);
        initComponents();
        this.panelMarcas = panel;
        this.setBackground(new java.awt.Color(0, 0, 0, 0));
        panelRound1.setFocusable(true);
        configurarPlaceholders();
        System.out.println("hola");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void cargarDatosEdicion(String id, String marca, String estado) {
        this.esEdicion = true;
        this.idMarcaOriginal = id;
        
        // Cambiamos el título visual
        jLabel3.setText("Editar Marca");
        
        // Llenamos la placa y cambiamos el color a oscuro
        flMarca.setText(marca);
        flMarca.setForeground(new java.awt.Color(60, 60, 60));
        
        cbxMarca.setSelectedItem(estado);
    }
    
    private void configurarPlaceholders() {
        aplicarPlaceholder(flMarca, "Ingrese la Marca");
    }

    private void aplicarPlaceholder(javax.swing.JTextField campo, String textoGuia) {
        // Configuración inicial del campo
        campo.setText(textoGuia);
        campo.setForeground(new java.awt.Color(153, 153, 153)); // Color gris para la guía

        // Añadimos el escuchador de foco
        campo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                // Si el texto actual es igual a la guía, lo borramos al entrar
                if (campo.getText().equals(textoGuia)) {
                    campo.setText("");
                    campo.setForeground(new java.awt.Color(60, 60, 60)); // Color oscuro al escribir
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                // Si el usuario sale del campo y lo dejó vacío, restauramos la guía
                if (campo.getText().trim().isEmpty()) {
                    campo.setText(textoGuia);
                    campo.setForeground(new java.awt.Color(153, 153, 153)); // Restaura el color gris
                }
            }
        });
    }
    private void aplicarPlaceholderComboBox(assets.ComboBoxRound combo) {
        // 1. Configuración inicial
        if (combo.getSelectedIndex() == -1) {
            combo.setForeground(new java.awt.Color(153, 153, 153)); // Gris
        } else {
            combo.setForeground(new java.awt.Color(60, 60, 60)); // Oscuro
        }

        // 2. Evento para cambiar el color al seleccionar
        combo.addItemListener(new java.awt.event.ItemListener() {
            @Override
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                    combo.setForeground(new java.awt.Color(60, 60, 60)); 
                } 
                else if (combo.getSelectedIndex() == -1) {
                    combo.setForeground(new java.awt.Color(153, 153, 153)); 
                }
            }
        });
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new assets.PanelRound();
        panelRound2 = new assets.PanelRound();
        btnCancelar = new assets.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnGuardar = new assets.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panelRound3 = new assets.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        panelRound15 = new assets.PanelRound();
        cbxMarca = new assets.ComboBoxRound();
        panelRound11 = new assets.PanelRound();
        flMarca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        panelRound1.setBackground(new java.awt.Color(253, 251, 250));
        panelRound1.setRoundBottomLeft(40);
        panelRound1.setRoundBottomRight(40);
        panelRound1.setRoundTopLeft(40);
        panelRound1.setRoundTopRight(40);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(252, 248, 243));
        panelRound2.setRoundBottomLeft(40);
        panelRound2.setRoundBottomRight(40);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setBorderColor(new java.awt.Color(204, 204, 204));
        btnCancelar.setBorderSize(1);
        btnCancelar.setPreferredSize(new java.awt.Dimension(133, 45));
        btnCancelar.setRoundBottomLeft(20);
        btnCancelar.setRoundBottomRight(20);
        btnCancelar.setRoundTopLeft(20);
        btnCancelar.setRoundTopRight(20);
        btnCancelar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        btnCancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        btnCancelar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 3, 30, 40));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel11.setText("Cancelar");
        btnCancelar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -3, 90, 50));

        panelRound2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(255, 153, 0));
        btnGuardar.setBorderColor(new java.awt.Color(0, 0, 0));
        btnGuardar.setPreferredSize(new java.awt.Dimension(133, 45));
        btnGuardar.setRoundBottomLeft(20);
        btnGuardar.setRoundBottomRight(20);
        btnGuardar.setRoundTopLeft(20);
        btnGuardar.setRoundTopRight(20);
        btnGuardar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        btnGuardar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconSaveWhite.png"))); // NOI18N
        btnGuardar.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 43, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Guardar");
        btnGuardar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -3, 80, 50));

        panelRound2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 150, 40));

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 619, 80));

        panelRound3.setBackground(new java.awt.Color(252, 248, 243));
        panelRound3.setRoundTopLeft(40);
        panelRound3.setRoundTopRight(40);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nueva Marca");
        panelRound3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 460, 40));

        panelRound1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 50));

        panelRound15.setBackground(new java.awt.Color(255, 255, 255));
        panelRound15.setBorderColor(new java.awt.Color(204, 204, 204));
        panelRound15.setBorderSize(1);
        panelRound15.setRoundBottomLeft(20);
        panelRound15.setRoundBottomRight(20);
        panelRound15.setRoundTopLeft(20);
        panelRound15.setRoundTopRight(20);
        panelRound15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxMarca.setEnabled(false);
        cbxMarca.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cbxMarca.setOpciones("Activo\nInactivo\n");
        panelRound15.add(cbxMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 230, 30));

        panelRound1.add(panelRound15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 250, 40));

        panelRound11.setBackground(new java.awt.Color(255, 255, 255));
        panelRound11.setBorderColor(new java.awt.Color(204, 204, 204));
        panelRound11.setBorderSize(1);
        panelRound11.setRoundBottomLeft(20);
        panelRound11.setRoundBottomRight(20);
        panelRound11.setRoundTopLeft(20);
        panelRound11.setRoundTopRight(20);
        panelRound11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        flMarca.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        flMarca.setForeground(new java.awt.Color(204, 204, 204));
        flMarca.setText("jTextField1");
        flMarca.setBorder(null);
        flMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flMarcaMouseClicked(evt);
            }
        });
        panelRound11.add(flMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 10, 220, 20));

        panelRound1.add(panelRound11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 250, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        // TODO add your handling code here:
        btnCancelar.setBackground(new java.awt.Color(242,242,242));
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        // TODO add your handling code here:
        btnCancelar.setBackground(Color.white);
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        Controls.catalogoController controller = new Controls.catalogoController(this);
        boolean operacionExitosa = false;
        
        if (esEdicion) {
            // Intentamos editar la marca
            operacionExitosa = controller.editarMarca(this, Integer.parseInt(idMarcaOriginal));
        } else {
            // Intentamos insertar la marca
            operacionExitosa = controller.insertarMarca(this);
        }
        
        // Si la operación de base de datos fue exitosa
        if (operacionExitosa) {
            if(panelMarcas != null){
                Controls.catalogoController c = new Controls.catalogoController(panelMarcas);
                c.listarMarcas(panelMarcas);
            }
            
            // Cerramos la ventana modal correctamente
            this.dispose(); 
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        // TODO add your handling code here:
        btnGuardar.setBackground(new Color(255,139,49));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        // TODO add your handling code here:
        btnGuardar.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void flMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flMarcaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_flMarcaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MarcasForm dialog = new MarcasForm(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private assets.PanelRound btnCancelar;
    private assets.PanelRound btnGuardar;
    public assets.ComboBoxRound cbxMarca;
    public javax.swing.JTextField flMarca;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private assets.PanelRound panelRound1;
    private assets.PanelRound panelRound11;
    private assets.PanelRound panelRound15;
    private assets.PanelRound panelRound2;
    private assets.PanelRound panelRound3;
    // End of variables declaration//GEN-END:variables
}
