/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.panels;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JPanel;


/**
 *
 * @author PC
 */
public class MarcasPanel extends javax.swing.JPanel {
        private String idClienteSeleccionado = null;

    /**
     * Creates new form ClientesPanel
     */
    private boolean isUnoSelected = false;
    private boolean isDosSelected = false;
    private boolean isTresSelected = false;
    private boolean isCuatroSelected = false;
    public MarcasPanel() {
        initComponents();
        
        Controls.catalogoController controller = new Controls.catalogoController(this);
        
        activarBotonesAccion(false);
        isUnoSelected = true;
        btnUno.setBackground(new Color(253, 239, 222));
        txtUno.setForeground(new Color(251, 124, 20));
        

    }
    // Método para activar o desactivar los botones dependiendo de si hay algo seleccionado
    private void activarBotonesAccion(boolean activar) {
        if (activar) {
            btnEditar.setCursor(new Cursor(Cursor.HAND_CURSOR));
            btnEditar.setBackground(new Color(254, 240, 228)); 
            txtEditarAlquiler.setForeground(new Color(251, 124, 20));
            iconEditarAlquiler.setIcon(new ImageIcon(getClass().getResource("/assets/iconPencilOrange.png")));
            btnEliminar.setCursor(new Cursor(Cursor.HAND_CURSOR));
            btnEliminar.setBackground(new Color(254, 234, 232));
            txtEliminarAlquiler.setForeground(new Color(255, 0, 51));
             iconEliminarAlquiler.setIcon(new ImageIcon(getClass().getResource("/assets/iconTrashRed.png")));
        } else {
           
            btnEditar.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            btnEditar.setBackground(new Color(245, 245, 245)); 
            txtEditarAlquiler.setForeground(new Color(170, 170, 170)); 
            iconEditarAlquiler.setIcon(new ImageIcon(getClass().getResource("/assets/iconPencilGray.png")));
            btnEliminar.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            btnEliminar.setBackground(new Color(245, 245, 245)); 
            txtEliminarAlquiler.setForeground(new Color(170, 170, 170)); 
            iconEliminarAlquiler.setIcon(new ImageIcon(getClass().getResource("/assets/iconTrashGray.png")));
            idClienteSeleccionado = null;
        }
    }
    private void resetearBotonesCatalogos() {
        isUnoSelected = false;
        isDosSelected = false;
        isTresSelected = false;
        isCuatroSelected = false;

        btnUno.setBackground(Color.WHITE);
        txtUno.setForeground(Color.BLACK);

        btnDos.setBackground(Color.WHITE);
        txtDos.setForeground(Color.BLACK);

        btnTres.setBackground(Color.WHITE);
        txtTres.setForeground(Color.BLACK);

        btnCuatro.setBackground(Color.WHITE);
        txtCuatro.setForeground(Color.BLACK);
    }
    public void showPanel(JPanel panel){
        panel.setSize(panelRound1.getWidth(), panelRound1.getHeight());
        panel.setLocation(0,0);

        panelRound1.removeAll();
        panelRound1.setLayout(new java.awt.BorderLayout());
        panelRound1.add(panel, java.awt.BorderLayout.CENTER);

        panelRound1.revalidate();
        panelRound1.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new assets.PanelRound();
        tableMarcas = new assets.TableRow();
        btnEditar = new assets.PanelRound();
        iconEditarAlquiler = new javax.swing.JLabel();
        txtEditarAlquiler = new javax.swing.JLabel();
        btnAgregar = new assets.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEliminar = new assets.PanelRound();
        iconEliminarAlquiler = new javax.swing.JLabel();
        txtEliminarAlquiler = new javax.swing.JLabel();
        panelRound2 = new assets.PanelRound();
        btnCuatro = new assets.PanelRound();
        txtCuatro = new javax.swing.JLabel();
        btnTres = new assets.PanelRound();
        txtTres = new javax.swing.JLabel();
        btnDos = new assets.PanelRound();
        txtDos = new javax.swing.JLabel();
        btnUno = new assets.PanelRound();
        txtUno = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(710, 502));

        panelRound1.setBackground(new java.awt.Color(253, 251, 250));
        panelRound1.setBorderColor(new java.awt.Color(204, 204, 204));
        panelRound1.setBorderSize(1);
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        tableMarcas.setNombresColumnas("ID, Marca, Estado");
        tableMarcas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMarcasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableMarcas, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableMarcas, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnEditar.setBackground(new java.awt.Color(254, 240, 228));
        btnEditar.setRoundBottomLeft(20);
        btnEditar.setRoundBottomRight(20);
        btnEditar.setRoundTopLeft(20);
        btnEditar.setRoundTopRight(20);
        btnEditar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });

        iconEditarAlquiler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconPencilOrange.png"))); // NOI18N

        txtEditarAlquiler.setBackground(new java.awt.Color(251, 124, 20));
        txtEditarAlquiler.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtEditarAlquiler.setForeground(new java.awt.Color(251, 124, 20));
        txtEditarAlquiler.setText("Editar");

        javax.swing.GroupLayout btnEditarLayout = new javax.swing.GroupLayout(btnEditar);
        btnEditar.setLayout(btnEditarLayout);
        btnEditarLayout.setHorizontalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditarLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(iconEditarAlquiler)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEditarAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnEditarLayout.setVerticalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconEditarAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
            .addComponent(txtEditarAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnAgregar.setBackground(new java.awt.Color(255, 153, 0));
        btnAgregar.setRoundBottomLeft(20);
        btnAgregar.setRoundBottomRight(20);
        btnAgregar.setRoundTopLeft(20);
        btnAgregar.setRoundTopRight(20);
        btnAgregar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMouseExited(evt);
            }
        });
        btnAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("+");
        btnAgregar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 36, 90));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nuevo");
        btnAgregar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, 150, 20));

        btnEliminar.setBackground(new java.awt.Color(254, 234, 232));
        btnEliminar.setRoundBottomLeft(20);
        btnEliminar.setRoundBottomRight(20);
        btnEliminar.setRoundTopLeft(20);
        btnEliminar.setRoundTopRight(20);
        btnEliminar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        iconEliminarAlquiler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconTrashRed.png"))); // NOI18N

        txtEliminarAlquiler.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtEliminarAlquiler.setForeground(new java.awt.Color(255, 0, 51));
        txtEliminarAlquiler.setText("Eliminar");

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconEliminarAlquiler)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEliminarAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconEliminarAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(txtEliminarAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setBorderColor(new java.awt.Color(204, 204, 204));
        panelRound2.setBorderSize(1);
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCuatro.setBackground(new java.awt.Color(255, 255, 255));
        btnCuatro.setRoundBottomLeft(10);
        btnCuatro.setRoundBottomRight(10);
        btnCuatro.setRoundTopLeft(10);
        btnCuatro.setRoundTopRight(10);
        btnCuatro.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnCuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCuatroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCuatroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCuatroMouseExited(evt);
            }
        });

        txtCuatro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCuatro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCuatro.setText("4");

        javax.swing.GroupLayout btnCuatroLayout = new javax.swing.GroupLayout(btnCuatro);
        btnCuatro.setLayout(btnCuatroLayout);
        btnCuatroLayout.setHorizontalGroup(
            btnCuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCuatro, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        btnCuatroLayout.setVerticalGroup(
            btnCuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCuatro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelRound2.add(btnCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 3, 40, 30));

        btnTres.setBackground(new java.awt.Color(255, 255, 255));
        btnTres.setRoundBottomLeft(10);
        btnTres.setRoundBottomRight(10);
        btnTres.setRoundTopLeft(10);
        btnTres.setRoundTopRight(10);
        btnTres.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnTres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTresMouseExited(evt);
            }
        });

        txtTres.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTres.setText("3");

        javax.swing.GroupLayout btnTresLayout = new javax.swing.GroupLayout(btnTres);
        btnTres.setLayout(btnTresLayout);
        btnTresLayout.setHorizontalGroup(
            btnTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTres, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        btnTresLayout.setVerticalGroup(
            btnTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelRound2.add(btnTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 3, 40, 30));

        btnDos.setBackground(new java.awt.Color(255, 255, 255));
        btnDos.setRoundBottomLeft(10);
        btnDos.setRoundBottomRight(10);
        btnDos.setRoundTopLeft(10);
        btnDos.setRoundTopRight(10);
        btnDos.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnDos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDosMouseExited(evt);
            }
        });

        txtDos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDos.setText("2");

        javax.swing.GroupLayout btnDosLayout = new javax.swing.GroupLayout(btnDos);
        btnDos.setLayout(btnDosLayout);
        btnDosLayout.setHorizontalGroup(
            btnDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDos, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        btnDosLayout.setVerticalGroup(
            btnDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelRound2.add(btnDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 3, 40, 30));

        btnUno.setBackground(new java.awt.Color(255, 255, 255));
        btnUno.setRoundBottomLeft(10);
        btnUno.setRoundBottomRight(10);
        btnUno.setRoundTopLeft(10);
        btnUno.setRoundTopRight(10);
        btnUno.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnUno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUnoMouseExited(evt);
            }
        });

        txtUno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtUno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtUno.setText("1");

        javax.swing.GroupLayout btnUnoLayout = new javax.swing.GroupLayout(btnUno);
        btnUno.setLayout(btnUnoLayout);
        btnUnoLayout.setHorizontalGroup(
            btnUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtUno, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        btnUnoLayout.setVerticalGroup(
            btnUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtUno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelRound2.add(btnUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked

        javax.swing.JFrame ventanaPadre = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        
        javax.swing.JPanel fondoOscuro = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                g.setColor(new java.awt.Color(0, 0, 0, 150)); 
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        fondoOscuro.setOpaque(false);
        fondoOscuro.addMouseListener(new java.awt.event.MouseAdapter() {}); 

        ventanaPadre.setGlassPane(fondoOscuro);
        fondoOscuro.setVisible(true);

        // AQUÍ ESTABA EL ERROR: Se agregó 'this' como tercer parámetro
        MarcasForm modal = new MarcasForm(ventanaPadre, true, this); 
        modal.setLocationRelativeTo(ventanaPadre); 
        modal.setVisible(true); 

        fondoOscuro.setVisible(false);
       
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseEntered
        // TODO add your handling code here:
        btnAgregar.setBackground(new Color(255,139,49));
    }//GEN-LAST:event_btnAgregarMouseEntered

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseExited
        // TODO add your handling code here:
        btnAgregar.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_btnAgregarMouseExited

    private void tableMarcasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMarcasMouseClicked
      int filaSeleccionada = tableMarcas.getTabla().getSelectedRow();

        if (filaSeleccionada != -1) {
            Object id = tableMarcas.getTabla().getValueAt(filaSeleccionada, 0);
            
            if (id != null && !id.toString().trim().isEmpty()) {
                // Guardamos el ID y encendemos los botones
                idClienteSeleccionado = id.toString();
                activarBotonesAccion(true);
            } else {
                // Si hace clic en una fila de relleno vacía, los apagamos
                activarBotonesAccion(false);
            }
        } else {
            // Si la fila es -1 (es decir, se deseleccionó al volver a hacer clic en la misma fila)
            activarBotonesAccion(false);
        }
    }//GEN-LAST:event_tableMarcasMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
     if (idClienteSeleccionado == null) return;

        int fila = tableMarcas.getTabla().getSelectedRow();
        if (fila == -1) return;

        String marca = tableMarcas.getTabla().getValueAt(fila, 1).toString();
        String estado = tableMarcas.getTabla().getValueAt(fila, 2).toString();

        javax.swing.JFrame ventanaPadre = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        
        javax.swing.JPanel fondoOscuro = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                g.setColor(new java.awt.Color(0, 0, 0, 150));
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        fondoOscuro.setOpaque(false);
        fondoOscuro.addMouseListener(new java.awt.event.MouseAdapter() {});

        ventanaPadre.setGlassPane(fondoOscuro);
        fondoOscuro.setVisible(true);

        MarcasForm modal = new MarcasForm(ventanaPadre, true, this); 
        modal.cargarDatosEdicion(idClienteSeleccionado, marca, estado);
        modal.setLocationRelativeTo(ventanaPadre);
        modal.setVisible(true);

        Controls.catalogoController controller = new Controls.catalogoController(this);
        controller.listarMarcas(this);

        fondoOscuro.setVisible(false);
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
       if (idClienteSeleccionado == null) return;
        
        int fila = tableMarcas.getTabla().getSelectedRow();
        if (fila == -1) return;

        Controls.catalogoController controller = new Controls.catalogoController(this);
        controller.eliminarMarcas(Integer.parseInt(idClienteSeleccionado));
        
        controller.listarMarcas(this);
        activarBotonesAccion(false);
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnUnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnoMouseClicked
        // TODO add your handling code here:
        resetearBotonesCatalogos();
        isUnoSelected = true;
        btnUno.setBackground(new Color(253, 239, 222));
        txtUno.setForeground(new Color(251, 124, 20));
    }//GEN-LAST:event_btnUnoMouseClicked

    private void btnUnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnoMouseEntered
        // TODO add your handling code here:
        if (!isUnoSelected) {
            btnUno.setBackground(new Color(253, 239, 222));
            txtUno.setForeground(new Color(251, 124, 20));
        }
    }//GEN-LAST:event_btnUnoMouseEntered

    private void btnUnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnoMouseExited
        // TODO add your handling code here:
        if (!isUnoSelected) {
            btnUno.setBackground(Color.WHITE);
            txtUno.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_btnUnoMouseExited

    private void btnDosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDosMouseClicked
        resetearBotonesCatalogos();
        isDosSelected = true;
        btnDos.setBackground(new Color(253, 239, 222));
        txtDos.setForeground(new Color(251, 124, 20));
        CatalogosPanel.instance.showPanel(new ModelosPanel());
        
    }//GEN-LAST:event_btnDosMouseClicked

    private void btnDosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDosMouseEntered
        if (!isDosSelected) {
            btnDos.setBackground(new Color(253, 239, 222));
            txtDos.setForeground(new Color(251, 124, 20));
        }
    }//GEN-LAST:event_btnDosMouseEntered

    private void btnDosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDosMouseExited
        if (!isDosSelected) {
            btnDos.setBackground(Color.WHITE);
            txtDos.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_btnDosMouseExited

    private void btnTresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTresMouseClicked
        resetearBotonesCatalogos();
        isTresSelected = true;
        btnTres.setBackground(new Color(253, 239, 222));
        txtTres.setForeground(new Color(251, 124, 20));
        CatalogosPanel.instance.showPanel(new TiposPanel());
    }//GEN-LAST:event_btnTresMouseClicked

    private void btnTresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTresMouseEntered
        if (!isTresSelected) {
            btnTres.setBackground(new Color(253, 239, 222));
            txtTres.setForeground(new Color(251, 124, 20));
        }
    }//GEN-LAST:event_btnTresMouseEntered

    private void btnTresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTresMouseExited
        if (!isTresSelected) {
            btnTres.setBackground(Color.WHITE);
            txtTres.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_btnTresMouseExited

    private void btnCuatroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCuatroMouseClicked
        resetearBotonesCatalogos();
        isCuatroSelected = true;
        btnCuatro.setBackground(new Color(253, 239, 222));
        txtCuatro.setForeground(new Color(251, 124, 20));
        CatalogosPanel.instance.showPanel(new ColoresPanel());
    }//GEN-LAST:event_btnCuatroMouseClicked

    private void btnCuatroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCuatroMouseEntered
        if (!isCuatroSelected) {
            btnCuatro.setBackground(new Color(253, 239, 222));
            txtCuatro.setForeground(new Color(251, 124, 20));
        }
    }//GEN-LAST:event_btnCuatroMouseEntered

    private void btnCuatroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCuatroMouseExited
        if (!isCuatroSelected) {
            btnCuatro.setBackground(Color.WHITE);
            txtCuatro.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_btnCuatroMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private assets.PanelRound btnAgregar;
    private assets.PanelRound btnCuatro;
    private assets.PanelRound btnDos;
    private assets.PanelRound btnEditar;
    private assets.PanelRound btnEliminar;
    private assets.PanelRound btnTres;
    private assets.PanelRound btnUno;
    private javax.swing.JLabel iconEditarAlquiler;
    private javax.swing.JLabel iconEliminarAlquiler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private assets.PanelRound panelRound1;
    private assets.PanelRound panelRound2;
    public assets.TableRow tableMarcas;
    private javax.swing.JLabel txtCuatro;
    private javax.swing.JLabel txtDos;
    private javax.swing.JLabel txtEditarAlquiler;
    private javax.swing.JLabel txtEliminarAlquiler;
    private javax.swing.JLabel txtTres;
    private javax.swing.JLabel txtUno;
    // End of variables declaration//GEN-END:variables
}
