/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.panels;

import Controls.alquileresController;
import Controls.vehiculosControls;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import DAO.alquileresDAO;

/**
 *
 * @author PC
 */
public class RentasPanel extends javax.swing.JPanel {
        private String idRentaSeleccionado = null;
         private RentasForm vista;
        private RentasPanel vista2;
        
        private alquileresController controlador;
    /**
     * Creates new form ClientesPanel
     */
    public RentasPanel() {
        initComponents();
        this.controlador = new alquileresController(null, this);
        controlador.mostrarTabla();
        activarBotonesAccion(false, "");
        

    }
    // Método para activar o desactivar los botones dependiendo de si hay algo seleccionado
    private void activarBotonesAccion(boolean activar,String estadoRenta) {
        if (activar) {
            btnEditarAlquiler.setCursor(new Cursor(Cursor.HAND_CURSOR));
            btnEditarAlquiler.setBackground(new Color(254, 240, 228)); 
            txtEditarAlquiler.setForeground(new Color(251, 124, 20));
            iconEditarAlquiler.setIcon(new ImageIcon(getClass().getResource("/assets/iconPencilOrange.png")));
            
            if (estadoRenta != null && estadoRenta.equalsIgnoreCase("Finalizado")) {
                btnFinalizarAlquiler.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                btnFinalizarAlquiler.setBackground(new Color(245, 245, 245));
                txtFinalizarAlquiler.setForeground(new Color(170, 170, 170));
                txtFinalizarAlquiler.setText("Finalizado");
                iconFinalizarAlquiler.setIcon(new ImageIcon(getClass().getResource("/assets/iconCheckGray.png")));
            } else {
                btnFinalizarAlquiler.setCursor(new Cursor(Cursor.HAND_CURSOR));
                btnFinalizarAlquiler.setBackground(new Color(234, 242, 222));
                txtFinalizarAlquiler.setForeground(new Color(40, 167, 69));
                txtFinalizarAlquiler.setText("Finalizar");
                iconFinalizarAlquiler.setIcon(new ImageIcon(getClass().getResource("/assets/iconCheckGreen.png")));
            }
        } else {
            btnEditarAlquiler.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            btnEditarAlquiler.setBackground(new Color(245, 245, 245)); 
            txtEditarAlquiler.setForeground(new Color(170, 170, 170)); 
            iconEditarAlquiler.setIcon(new ImageIcon(getClass().getResource("/assets/iconPencilGray.png")));
            
            btnFinalizarAlquiler.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            btnFinalizarAlquiler.setBackground(new Color(245, 245, 245)); 
            txtFinalizarAlquiler.setForeground(new Color(170, 170, 170)); 
            txtFinalizarAlquiler.setText("Finalizar");
            
            // AQUÍ ESTABA EL DETALLE: Usamos el ícono gris inactivo al iniciar
            iconFinalizarAlquiler.setIcon(new ImageIcon(getClass().getResource("/assets/iconCheckGray.png")));
            
            idRentaSeleccionado = null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new assets.PanelRound();
        tableClientes = new assets.TableRow();
        btnEditarAlquiler = new assets.PanelRound();
        iconEditarAlquiler = new javax.swing.JLabel();
        txtEditarAlquiler = new javax.swing.JLabel();
        btnAgregarAlquiler = new assets.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnFinalizarAlquiler = new assets.PanelRound();
        iconFinalizarAlquiler = new javax.swing.JLabel();
        txtFinalizarAlquiler = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(710, 502));

        panelRound1.setBackground(new java.awt.Color(253, 251, 250));
        panelRound1.setBorderColor(new java.awt.Color(204, 204, 204));
        panelRound1.setBorderSize(1);
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        tableClientes.setNombresColumnas("ID, Cliente, Vehiculo, Fecha, Total, Dias, Estado");
        tableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClientesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnEditarAlquiler.setBackground(new java.awt.Color(254, 240, 228));
        btnEditarAlquiler.setRoundBottomLeft(20);
        btnEditarAlquiler.setRoundBottomRight(20);
        btnEditarAlquiler.setRoundTopLeft(20);
        btnEditarAlquiler.setRoundTopRight(20);
        btnEditarAlquiler.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnEditarAlquiler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarAlquilerMouseClicked(evt);
            }
        });

        iconEditarAlquiler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconPencilOrange.png"))); // NOI18N

        txtEditarAlquiler.setBackground(new java.awt.Color(251, 124, 20));
        txtEditarAlquiler.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtEditarAlquiler.setForeground(new java.awt.Color(251, 124, 20));
        txtEditarAlquiler.setText("Editar");

        javax.swing.GroupLayout btnEditarAlquilerLayout = new javax.swing.GroupLayout(btnEditarAlquiler);
        btnEditarAlquiler.setLayout(btnEditarAlquilerLayout);
        btnEditarAlquilerLayout.setHorizontalGroup(
            btnEditarAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditarAlquilerLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(iconEditarAlquiler)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEditarAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnEditarAlquilerLayout.setVerticalGroup(
            btnEditarAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconEditarAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
            .addComponent(txtEditarAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnAgregarAlquiler.setBackground(new java.awt.Color(255, 153, 0));
        btnAgregarAlquiler.setRoundBottomLeft(20);
        btnAgregarAlquiler.setRoundBottomRight(20);
        btnAgregarAlquiler.setRoundTopLeft(20);
        btnAgregarAlquiler.setRoundTopRight(20);
        btnAgregarAlquiler.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnAgregarAlquiler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarAlquilerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarAlquilerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarAlquilerMouseExited(evt);
            }
        });
        btnAgregarAlquiler.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("+");
        btnAgregarAlquiler.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -30, 36, 90));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registrar Alquiler");
        btnAgregarAlquiler.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 9, 180, 20));

        btnFinalizarAlquiler.setBackground(new java.awt.Color(234, 242, 222));
        btnFinalizarAlquiler.setRoundBottomLeft(20);
        btnFinalizarAlquiler.setRoundBottomRight(20);
        btnFinalizarAlquiler.setRoundTopLeft(20);
        btnFinalizarAlquiler.setRoundTopRight(20);
        btnFinalizarAlquiler.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnFinalizarAlquiler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinalizarAlquilerMouseClicked(evt);
            }
        });

        iconFinalizarAlquiler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconCheckGreen.png"))); // NOI18N

        txtFinalizarAlquiler.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtFinalizarAlquiler.setForeground(new java.awt.Color(40, 167, 69));
        txtFinalizarAlquiler.setText("Finalizar");

        javax.swing.GroupLayout btnFinalizarAlquilerLayout = new javax.swing.GroupLayout(btnFinalizarAlquiler);
        btnFinalizarAlquiler.setLayout(btnFinalizarAlquilerLayout);
        btnFinalizarAlquilerLayout.setHorizontalGroup(
            btnFinalizarAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFinalizarAlquilerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconFinalizarAlquiler)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFinalizarAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnFinalizarAlquilerLayout.setVerticalGroup(
            btnFinalizarAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFinalizarAlquilerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnFinalizarAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconFinalizarAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(txtFinalizarAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditarAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFinalizarAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnAgregarAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFinalizarAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarAlquilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarAlquilerMouseClicked

        javax.swing.JFrame ventanaPadre = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        
        // 2. Creamos el efecto de fondo oscuro
        javax.swing.JPanel fondoOscuro = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                g.setColor(new java.awt.Color(0, 0, 0, 150)); // Negro con transparencia
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        fondoOscuro.setOpaque(false);
        fondoOscuro.addMouseListener(new java.awt.event.MouseAdapter() {}); // Bloquea los clics de atrás

        //Encendemos el fondo oscuro
        ventanaPadre.setGlassPane(fondoOscuro);
        fondoOscuro.setVisible(true);

        RentasForm modal = new RentasForm(ventanaPadre, true,this); 
        modal.setLocationRelativeTo(ventanaPadre); // Lo centra en la pantalla
        
        modal.setVisible(true); // Abre la ventana (el código se pausa aquí hasta que cierres el modal)

        //SApagamos el fondo oscuro cuando se cierra el JDialog
        fondoOscuro.setVisible(false);
       
    }//GEN-LAST:event_btnAgregarAlquilerMouseClicked

    private void btnAgregarAlquilerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarAlquilerMouseEntered
        // TODO add your handling code here:
        btnAgregarAlquiler.setBackground(new Color(255,139,49));
    }//GEN-LAST:event_btnAgregarAlquilerMouseEntered

    private void btnAgregarAlquilerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarAlquilerMouseExited
        // TODO add your handling code here:
        btnAgregarAlquiler.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_btnAgregarAlquilerMouseExited

    private void tableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClientesMouseClicked
        int filaSeleccionada = tableClientes.getTabla().getSelectedRow();

        if (filaSeleccionada != -1) {
            Object id = tableClientes.getTabla().getValueAt(filaSeleccionada, 0);
            
            if (id != null && !id.toString().trim().isEmpty()) {
                idRentaSeleccionado = id.toString();
                String estadoActual = tableClientes.getTabla().getValueAt(filaSeleccionada, 6).toString();
                activarBotonesAccion(true, estadoActual);
            } else {
                activarBotonesAccion(false, "");
            }
        } else {
            activarBotonesAccion(false, "");
        }
    }//GEN-LAST:event_tableClientesMouseClicked

    private void btnEditarAlquilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarAlquilerMouseClicked
        if (idRentaSeleccionado == null) return;

        int fila = tableClientes.getTabla().getSelectedRow();
        if (fila == -1) return;

        // ORDEN EXACTO DE TU TABLA: ID(0), Cliente(1), Vehiculo(2), Fecha(3), Total(4), Dias(5), Estado(6)
        String cliente = tableClientes.getTabla().getValueAt(fila, 1).toString();
        String vehiculo = tableClientes.getTabla().getValueAt(fila, 2).toString();
        String fecha = tableClientes.getTabla().getValueAt(fila, 3).toString();
        

        // CORREGIDO: El índice 4 es Total y el índice 5 son Días
        String total = tableClientes.getTabla().getValueAt(fila, 4).toString().replace("$", "").trim();
        String dias = tableClientes.getTabla().getValueAt(fila, 5).toString();
        

        String estado = tableClientes.getTabla().getValueAt(fila, 6).toString();

        javax.swing.JFrame ventanaPadre = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        
        javax.swing.JPanel fondoOscuro = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                g.setColor(new java.awt.Color(0, 0, 0, 150));
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        fondoOscuro.setOpaque(false);
        fondoOscuro.addMouseListener(new java.awt.event.MouseAdapter() {});

        ventanaPadre.setGlassPane(fondoOscuro);
        fondoOscuro.setVisible(true);

        RentasForm modal = new RentasForm(ventanaPadre, true, this); 
        
        // Respetamos el mismo orden: id, cliente, vehiculo, fecha, dias, total, estado
        modal.cargarDatosEdicion(idRentaSeleccionado, cliente, vehiculo, fecha, total, dias, estado);
        
        modal.setLocationRelativeTo(ventanaPadre);
        modal.setVisible(true);

        fondoOscuro.setVisible(false);

    }//GEN-LAST:event_btnEditarAlquilerMouseClicked

    private void btnFinalizarAlquilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizarAlquilerMouseClicked
        if (idRentaSeleccionado == null) return;
        
        String accionBoton = txtFinalizarAlquiler.getText();
        if (accionBoton.equalsIgnoreCase("Finalizado")) {
            return; 
        }
        
        int fila = tableClientes.getTabla().getSelectedRow();
        if (fila == -1) return;

        int idAlquiler = Integer.parseInt(idRentaSeleccionado);
        
        controlador.finalizarAlquiler(idAlquiler);
        
        controlador.mostrarTabla();
        activarBotonesAccion(false, "");
        tableClientes.getTabla().clearSelection();
    }//GEN-LAST:event_btnFinalizarAlquilerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private assets.PanelRound btnAgregarAlquiler;
    private assets.PanelRound btnEditarAlquiler;
    private assets.PanelRound btnFinalizarAlquiler;
    private javax.swing.JLabel iconEditarAlquiler;
    private javax.swing.JLabel iconFinalizarAlquiler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private assets.PanelRound panelRound1;
    public assets.TableRow tableClientes;
    private javax.swing.JLabel txtEditarAlquiler;
    public javax.swing.JLabel txtFinalizarAlquiler;
    // End of variables declaration//GEN-END:variables
}
