/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views.panels;

import java.awt.Color;
import java.awt.Cursor;
import DAO.alquileresDAO;
import Models.alquileres;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JOptionPane;
import Views.panels.RentasPanel;

/**
 *
 * @author PC
 */
public class RentasForm extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RentasForm.class.getName());
    private boolean esEdicion = false;
    private String idVehiculoOriginal = "";
    /**
     * Creates new form ClientesForm
     */
    alquileresDAO dao = new alquileresDAO();
    public RentasForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setBackground(new java.awt.Color(0, 0, 0, 0));
        panelRound1.setFocusable(true);
        configurarPlaceholders();
        cargarClientes();
        cargarVehiculos();
    }
    private void cargarClientes(){

    cbxAlquilerCliente.removeAllItems();

    List<Object[]> lista = dao.listarClientesActivos();

    for(Object[] dato : lista){

        cbxAlquilerCliente.addItem(
                dato[0] + " - " + dato[1]
        );

    }
}
    private void cargarVehiculos(){

    cbxAlquilerVehiculo.removeAllItems();

    List<Object[]> lista = dao.listarVehiculosDisponibles();

    for(Object[] dato : lista){

        cbxAlquilerVehiculo.addItem(
                dato[0] + " - " + dato[1]
        );

    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void cargarDatosEdicion(String id, String cliente, String vehiculo, String fecha, String dias, String total, String estado) {
        this.esEdicion = true;
        this.idVehiculoOriginal = id;
        
        // Cambiamos el título visual
        jLabel3.setText("Editar Alquiler");
        jLabel4.setText("Modifique la Información del Alquiler");
        
        // Llenamos los campos de texto y cambiamos el color a oscuro
        flFecha.setText(fecha);
        flFecha.setForeground(new java.awt.Color(60, 60, 60));
        
        flDias.setText(dias);
        flDias.setForeground(new java.awt.Color(60, 60, 60));
        
        flTotal.setText(total);
        flTotal.setForeground(new java.awt.Color(60, 60, 60));
        
        // Llenamos los ComboBox
        cbxAlquilerCliente.setSelectedItem(cliente);
        cbxAlquilerVehiculo.setSelectedItem(vehiculo);
        cbxEstadoCliente.setSelectedItem(estado);
    }
    
    private void configurarPlaceholders() {
        aplicarPlaceholder(flFecha, "Ingrese la Fecha");
        aplicarPlaceholder(flDias, "Ingrese los Días");
        aplicarPlaceholder(flTotal, "Ingrese el Total");
       
        aplicarPlaceholderComboBox(cbxAlquilerCliente);
        aplicarPlaceholderComboBox(cbxAlquilerVehiculo);
        aplicarPlaceholderComboBox(cbxEstadoCliente);
    }

    private void aplicarPlaceholder(javax.swing.JTextField campo, String textoGuia) {
        // Configuración inicial del campo
        campo.setText(textoGuia);
        campo.setForeground(new java.awt.Color(153, 153, 153)); // Color gris para la guía

        // Añadimos el escuchador de foco
        campo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                // Si el texto actual es igual a la guía, lo borramos al entrar
                if (campo.getText().equals(textoGuia)) {
                    campo.setText("");
                    campo.setForeground(new java.awt.Color(60, 60, 60)); // Color oscuro al escribir
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                // Si el usuario sale del campo y lo dejó vacío, restauramos la guía
                if (campo.getText().trim().isEmpty()) {
                    campo.setText(textoGuia);
                    campo.setForeground(new java.awt.Color(153, 153, 153)); // Restaura el color gris
                }
            }
        });
    }
    private void aplicarPlaceholderComboBox(assets.ComboBoxRound combo) {
        // 1. Configuración inicial
        if (combo.getSelectedIndex() == -1) {
            combo.setForeground(new java.awt.Color(153, 153, 153)); // Gris
        } else {
            combo.setForeground(new java.awt.Color(60, 60, 60)); // Oscuro
        }

        // 2. Evento para cambiar el color al seleccionar
        combo.addItemListener(new java.awt.event.ItemListener() {
            @Override
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                    combo.setForeground(new java.awt.Color(60, 60, 60)); 
                } 
                else if (combo.getSelectedIndex() == -1) {
                    combo.setForeground(new java.awt.Color(153, 153, 153)); 
                }
            }
        });
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new assets.PanelRound();
        panelRound2 = new assets.PanelRound();
        btnCancelar = new assets.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnGuardar = new assets.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panelRound3 = new assets.PanelRound();
        panelRound4 = new assets.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelRound5 = new assets.PanelRound();
        flTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        panelRound11 = new assets.PanelRound();
        cbxAlquilerCliente = new assets.ComboBoxRound();
        jLabel8 = new javax.swing.JLabel();
        panelRound12 = new assets.PanelRound();
        cbxAlquilerVehiculo = new assets.ComboBoxRound();
        jLabel9 = new javax.swing.JLabel();
        panelRound13 = new assets.PanelRound();
        flFecha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelRound14 = new assets.PanelRound();
        flDias = new javax.swing.JTextField();
        panelRound15 = new assets.PanelRound();
        cbxEstadoCliente = new assets.ComboBoxRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        panelRound1.setBackground(new java.awt.Color(253, 251, 250));
        panelRound1.setRoundBottomLeft(40);
        panelRound1.setRoundBottomRight(40);
        panelRound1.setRoundTopLeft(40);
        panelRound1.setRoundTopRight(40);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(252, 248, 243));
        panelRound2.setRoundBottomLeft(40);
        panelRound2.setRoundBottomRight(40);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setBorderColor(new java.awt.Color(204, 204, 204));
        btnCancelar.setBorderSize(1);
        btnCancelar.setPreferredSize(new java.awt.Dimension(133, 45));
        btnCancelar.setRoundBottomLeft(20);
        btnCancelar.setRoundBottomRight(20);
        btnCancelar.setRoundTopLeft(20);
        btnCancelar.setRoundTopRight(20);
        btnCancelar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        btnCancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setText("X");
        btnCancelar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 33));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel11.setText("Cancelar");
        btnCancelar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 15, 90, -1));

        panelRound2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, 50));

        btnGuardar.setBackground(new java.awt.Color(255, 153, 0));
        btnGuardar.setBorderColor(new java.awt.Color(0, 0, 0));
        btnGuardar.setPreferredSize(new java.awt.Dimension(133, 45));
        btnGuardar.setRoundBottomLeft(20);
        btnGuardar.setRoundBottomRight(20);
        btnGuardar.setRoundTopLeft(20);
        btnGuardar.setRoundTopRight(20);
        btnGuardar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        btnGuardar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconSaveWhite.png"))); // NOI18N
        btnGuardar.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 43, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Guardar");
        btnGuardar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -3, 80, 50));

        panelRound2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 150, -1));

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 619, 80));

        panelRound3.setBackground(new java.awt.Color(252, 248, 243));
        panelRound3.setRoundTopLeft(40);
        panelRound3.setRoundTopRight(40);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setBorderColor(new java.awt.Color(255, 153, 0));
        panelRound4.setBorderSize(1);
        panelRound4.setRoundBottomLeft(20);
        panelRound4.setRoundBottomRight(20);
        panelRound4.setRoundTopLeft(20);
        panelRound4.setRoundTopRight(20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconGroupOrange2.png"))); // NOI18N

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        panelRound3.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 60, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("Nuevo Vehiculo");
        panelRound3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Ingrese la Informacion del Vehiculos");
        panelRound3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        panelRound1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 619, 90));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel6.setText("Cliente");
        panelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        panelRound5.setBackground(new java.awt.Color(255, 255, 255));
        panelRound5.setBorderColor(new java.awt.Color(204, 204, 204));
        panelRound5.setBorderSize(1);
        panelRound5.setRoundBottomLeft(20);
        panelRound5.setRoundBottomRight(20);
        panelRound5.setRoundTopLeft(20);
        panelRound5.setRoundTopRight(20);
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        flTotal.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        flTotal.setForeground(new java.awt.Color(204, 204, 204));
        flTotal.setText("jTextField1");
        flTotal.setBorder(null);
        panelRound5.add(flTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 10, 220, 20));

        panelRound1.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 250, 40));

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel7.setText("Vehiculo");
        panelRound1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        panelRound11.setBackground(new java.awt.Color(255, 255, 255));
        panelRound11.setBorderColor(new java.awt.Color(204, 204, 204));
        panelRound11.setBorderSize(1);
        panelRound11.setRoundBottomLeft(20);
        panelRound11.setRoundBottomRight(20);
        panelRound11.setRoundTopLeft(20);
        panelRound11.setRoundTopRight(20);
        panelRound11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxAlquilerCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cbxAlquilerCliente.setOpciones("Activo\nInactivo\n");
        cbxAlquilerCliente.addActionListener(this::cbxAlquilerClienteActionPerformed);
        panelRound11.add(cbxAlquilerCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 230, 30));

        panelRound1.add(panelRound11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 250, 40));

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel8.setText("Fecha");
        panelRound1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        panelRound12.setBackground(new java.awt.Color(255, 255, 255));
        panelRound12.setBorderColor(new java.awt.Color(204, 204, 204));
        panelRound12.setBorderSize(1);
        panelRound12.setRoundBottomLeft(20);
        panelRound12.setRoundBottomRight(20);
        panelRound12.setRoundTopLeft(20);
        panelRound12.setRoundTopRight(20);
        panelRound12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxAlquilerVehiculo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cbxAlquilerVehiculo.setOpciones("Activo\nInactivo\n");
        cbxAlquilerVehiculo.addActionListener(this::cbxAlquilerVehiculoActionPerformed);
        panelRound12.add(cbxAlquilerVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 230, 30));

        panelRound1.add(panelRound12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 250, 40));

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel9.setText("Total");
        panelRound1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        panelRound13.setBackground(new java.awt.Color(255, 255, 255));
        panelRound13.setBorderColor(new java.awt.Color(204, 204, 204));
        panelRound13.setBorderSize(1);
        panelRound13.setRoundBottomLeft(20);
        panelRound13.setRoundBottomRight(20);
        panelRound13.setRoundTopLeft(20);
        panelRound13.setRoundTopRight(20);
        panelRound13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        flFecha.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        flFecha.setForeground(new java.awt.Color(204, 204, 204));
        flFecha.setText("jTextField1");
        flFecha.setBorder(null);
        panelRound13.add(flFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 10, 220, 20));

        panelRound1.add(panelRound13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 250, 40));

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel10.setText("Dias");
        panelRound1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel5.setText("Estado");
        panelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        panelRound14.setBackground(new java.awt.Color(255, 255, 255));
        panelRound14.setBorderColor(new java.awt.Color(204, 204, 204));
        panelRound14.setBorderSize(1);
        panelRound14.setRoundBottomLeft(20);
        panelRound14.setRoundBottomRight(20);
        panelRound14.setRoundTopLeft(20);
        panelRound14.setRoundTopRight(20);
        panelRound14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        flDias.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        flDias.setForeground(new java.awt.Color(204, 204, 204));
        flDias.setText("jTextField1");
        flDias.setBorder(null);
        panelRound14.add(flDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 10, 220, 20));

        panelRound1.add(panelRound14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 250, 40));

        panelRound15.setBackground(new java.awt.Color(255, 255, 255));
        panelRound15.setBorderColor(new java.awt.Color(204, 204, 204));
        panelRound15.setBorderSize(1);
        panelRound15.setRoundBottomLeft(20);
        panelRound15.setRoundBottomRight(20);
        panelRound15.setRoundTopLeft(20);
        panelRound15.setRoundTopRight(20);
        panelRound15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxEstadoCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cbxEstadoCliente.setOpciones("Disponible\nAlquilado\n");
        panelRound15.add(cbxEstadoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 230, 30));

        panelRound1.add(panelRound15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 250, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        // TODO add your handling code here:
        btnCancelar.setBackground(new java.awt.Color(242,242,242));
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        // TODO add your handling code here:
        btnCancelar.setBackground(Color.white);
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
           try {

        alquileres a = new alquileres();

        // Obtener cliente seleccionado del ComboBox
        String cliente = cbxAlquilerCliente.getSelectedItem().toString();

        int idCliente = Integer.parseInt(
                cliente.split(" - ")[0]
        );


        // Obtener vehículo seleccionado del ComboBox
        String vehiculo = cbxAlquilerVehiculo.getSelectedItem().toString();

        int idVehiculo = Integer.parseInt(
                vehiculo.split(" - ")[0]
        );


        // Guardar IDs de las claves foráneas
        a.setFkIdCliente(idCliente);
        a.setFkIdVehiculo(idVehiculo);


        // Datos del alquiler
        a.setFechaAlquiler(flFecha.getText());
        a.setTotal(Double.parseDouble(flTotal.getText()));
        a.setDias(Integer.parseInt(flDias.getText()));

        a.setEstado(
            cbxEstadoCliente.getSelectedItem().toString()
        );


        alquileresDAO dao = new alquileresDAO();


        if (esEdicion) {

            a.setIdAlquiler(Integer.parseInt(idVehiculoOriginal));

            if (dao.editarAlquiler(a)) {

                JOptionPane.showMessageDialog(this,
                    "Alquiler actualizado");

                dispose();

            } else {

                JOptionPane.showMessageDialog(this,
                    "Error al actualizar");

            }


        } else {


            if (dao.insertarAlquiler(a)) {

                JOptionPane.showMessageDialog(this,
                    "Alquiler registrado");

                dispose();

            } else {

                JOptionPane.showMessageDialog(this,
                    "Error al registrar");

            }

        }


    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage());

    }

    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        // TODO add your handling code here:
        btnGuardar.setBackground(new Color(255,139,49));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        // TODO add your handling code here:
        btnGuardar.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void cbxAlquilerClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAlquilerClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAlquilerClienteActionPerformed

    private void cbxAlquilerVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAlquilerVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAlquilerVehiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                RentasForm dialog = new RentasForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private assets.PanelRound btnCancelar;
    private assets.PanelRound btnGuardar;
    public assets.ComboBoxRound cbxAlquilerCliente;
    public assets.ComboBoxRound cbxAlquilerVehiculo;
    public assets.ComboBoxRound cbxEstadoCliente;
    public javax.swing.JTextField flDias;
    public javax.swing.JTextField flFecha;
    public javax.swing.JTextField flTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private assets.PanelRound panelRound1;
    private assets.PanelRound panelRound11;
    private assets.PanelRound panelRound12;
    private assets.PanelRound panelRound13;
    private assets.PanelRound panelRound14;
    private assets.PanelRound panelRound15;
    private assets.PanelRound panelRound2;
    private assets.PanelRound panelRound3;
    private assets.PanelRound panelRound4;
    private assets.PanelRound panelRound5;
    // End of variables declaration//GEN-END:variables
}
