/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.panels;

import Controls.alquileresController;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.ImageIcon;


/**
 *
 * @author PC
 */
public class RentasPanel extends javax.swing.JPanel {
        private String idClienteSeleccionado = null;

    /**
     * Creates new form ClientesPanel
     */
    public RentasPanel() {
        initComponents();
        alquileresController controller = new alquileresController(this);
        controller.listar();
        activarBotonesAccion(false);
        

    }
    // Método para activar o desactivar los botones dependiendo de si hay algo seleccionado
    private void activarBotonesAccion(boolean activar) {
        if (activar) {
            btnEditarAlquiler.setCursor(new Cursor(Cursor.HAND_CURSOR));
            btnEditarAlquiler.setBackground(new Color(254, 240, 228)); 
            txtEditarAlquiler.setForeground(new Color(251, 124, 20));
            iconEditarAlquiler.setIcon(new ImageIcon(getClass().getResource("/assets/iconPencilOrange.png")));
            btnEliminarAlquiler.setCursor(new Cursor(Cursor.HAND_CURSOR));
            btnEliminarAlquiler.setBackground(new Color(254, 234, 232));
            txtEliminarAlquiler.setForeground(new Color(255, 0, 51));
             iconEliminarAlquiler.setIcon(new ImageIcon(getClass().getResource("/assets/iconTrashRed.png")));
        } else {
           
            btnEditarAlquiler.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            btnEditarAlquiler.setBackground(new Color(245, 245, 245)); 
            txtEditarAlquiler.setForeground(new Color(170, 170, 170)); 
            iconEditarAlquiler.setIcon(new ImageIcon(getClass().getResource("/assets/iconPencilGray.png")));
            btnEliminarAlquiler.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            btnEliminarAlquiler.setBackground(new Color(245, 245, 245)); 
            txtEliminarAlquiler.setForeground(new Color(170, 170, 170)); 
            iconEliminarAlquiler.setIcon(new ImageIcon(getClass().getResource("/assets/iconTrashGray.png")));
            idClienteSeleccionado = null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new assets.PanelRound();
        tableClientes = new assets.TableRow();
        btnEditarAlquiler = new assets.PanelRound();
        iconEditarAlquiler = new javax.swing.JLabel();
        txtEditarAlquiler = new javax.swing.JLabel();
        btnAgregarAlquiler = new assets.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEliminarAlquiler = new assets.PanelRound();
        iconEliminarAlquiler = new javax.swing.JLabel();
        txtEliminarAlquiler = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(710, 502));

        panelRound1.setBackground(new java.awt.Color(253, 251, 250));
        panelRound1.setBorderColor(new java.awt.Color(204, 204, 204));
        panelRound1.setBorderSize(1);
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        tableClientes.setNombresColumnas("ID, Cliente, Vehiculo, Fecha, Total, Dias, Estado");
        tableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClientesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnEditarAlquiler.setBackground(new java.awt.Color(254, 240, 228));
        btnEditarAlquiler.setRoundBottomLeft(20);
        btnEditarAlquiler.setRoundBottomRight(20);
        btnEditarAlquiler.setRoundTopLeft(20);
        btnEditarAlquiler.setRoundTopRight(20);
        btnEditarAlquiler.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnEditarAlquiler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarAlquilerMouseClicked(evt);
            }
        });

        iconEditarAlquiler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconPencilOrange.png"))); // NOI18N

        txtEditarAlquiler.setBackground(new java.awt.Color(251, 124, 20));
        txtEditarAlquiler.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtEditarAlquiler.setForeground(new java.awt.Color(251, 124, 20));
        txtEditarAlquiler.setText("Editar");

        javax.swing.GroupLayout btnEditarAlquilerLayout = new javax.swing.GroupLayout(btnEditarAlquiler);
        btnEditarAlquiler.setLayout(btnEditarAlquilerLayout);
        btnEditarAlquilerLayout.setHorizontalGroup(
            btnEditarAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditarAlquilerLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(iconEditarAlquiler)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEditarAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnEditarAlquilerLayout.setVerticalGroup(
            btnEditarAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconEditarAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
            .addComponent(txtEditarAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnAgregarAlquiler.setBackground(new java.awt.Color(255, 153, 0));
        btnAgregarAlquiler.setRoundBottomLeft(20);
        btnAgregarAlquiler.setRoundBottomRight(20);
        btnAgregarAlquiler.setRoundTopLeft(20);
        btnAgregarAlquiler.setRoundTopRight(20);
        btnAgregarAlquiler.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnAgregarAlquiler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarAlquilerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarAlquilerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarAlquilerMouseExited(evt);
            }
        });
        btnAgregarAlquiler.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("+");
        btnAgregarAlquiler.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -30, 36, 90));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registrar Alquiler");
        btnAgregarAlquiler.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 9, 180, 20));

        btnEliminarAlquiler.setBackground(new java.awt.Color(254, 234, 232));
        btnEliminarAlquiler.setRoundBottomLeft(20);
        btnEliminarAlquiler.setRoundBottomRight(20);
        btnEliminarAlquiler.setRoundTopLeft(20);
        btnEliminarAlquiler.setRoundTopRight(20);
        btnEliminarAlquiler.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnEliminarAlquiler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarAlquilerMouseClicked(evt);
            }
        });

        iconEliminarAlquiler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconTrashRed.png"))); // NOI18N

        txtEliminarAlquiler.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtEliminarAlquiler.setForeground(new java.awt.Color(255, 0, 51));
        txtEliminarAlquiler.setText("Eliminar");

        javax.swing.GroupLayout btnEliminarAlquilerLayout = new javax.swing.GroupLayout(btnEliminarAlquiler);
        btnEliminarAlquiler.setLayout(btnEliminarAlquilerLayout);
        btnEliminarAlquilerLayout.setHorizontalGroup(
            btnEliminarAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarAlquilerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconEliminarAlquiler)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEliminarAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnEliminarAlquilerLayout.setVerticalGroup(
            btnEliminarAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarAlquilerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnEliminarAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconEliminarAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(txtEliminarAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditarAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnAgregarAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarAlquilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarAlquilerMouseClicked

        javax.swing.JFrame ventanaPadre = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        
        // 2. Creamos el efecto de fondo oscuro
        javax.swing.JPanel fondoOscuro = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                g.setColor(new java.awt.Color(0, 0, 0, 150)); // Negro con transparencia
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        fondoOscuro.setOpaque(false);
        fondoOscuro.addMouseListener(new java.awt.event.MouseAdapter() {}); // Bloquea los clics de atrás

        //Encendemos el fondo oscuro
        ventanaPadre.setGlassPane(fondoOscuro);
        fondoOscuro.setVisible(true);

        RentasForm modal = new RentasForm(ventanaPadre, true); 
        modal.setLocationRelativeTo(ventanaPadre); // Lo centra en la pantalla
        
        modal.setVisible(true); // Abre la ventana (el código se pausa aquí hasta que cierres el modal)

        //SApagamos el fondo oscuro cuando se cierra el JDialog
        fondoOscuro.setVisible(false);
       
    }//GEN-LAST:event_btnAgregarAlquilerMouseClicked

    private void btnAgregarAlquilerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarAlquilerMouseEntered
        // TODO add your handling code here:
        btnAgregarAlquiler.setBackground(new Color(255,139,49));
    }//GEN-LAST:event_btnAgregarAlquilerMouseEntered

    private void btnAgregarAlquilerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarAlquilerMouseExited
        // TODO add your handling code here:
        btnAgregarAlquiler.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_btnAgregarAlquilerMouseExited

    private void tableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClientesMouseClicked
      int filaSeleccionada = tableClientes.getTabla().getSelectedRow();

        if (filaSeleccionada != -1) {
            Object id = tableClientes.getTabla().getValueAt(filaSeleccionada, 0);
            
            if (id != null && !id.toString().trim().isEmpty()) {
                // Guardamos el ID y encendemos los botones
                idClienteSeleccionado = id.toString();
                activarBotonesAccion(true);
            } else {
                // Si hace clic en una fila de relleno vacía, los apagamos
                activarBotonesAccion(false);
            }
        } else {
            // Si la fila es -1 (es decir, se deseleccionó al volver a hacer clic en la misma fila)
            activarBotonesAccion(false);
        }
    }//GEN-LAST:event_tableClientesMouseClicked

    private void btnEditarAlquilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarAlquilerMouseClicked
     if (idClienteSeleccionado == null) return;

        // Obtenemos la fila
        int fila = tableClientes.getTabla().getSelectedRow();
        
        // Evitamos que el código continúe si se perdió la selección visual
        if (fila == -1) return;

        // Extraer los datos basándonos en tu tabla: ID, Cliente, Vehiculo, Fecha, Total, Dias, Estado
        String cliente = tableClientes.getTabla().getValueAt(fila, 1).toString();
        String vehiculo = tableClientes.getTabla().getValueAt(fila, 2).toString();
        String fecha = tableClientes.getTabla().getValueAt(fila, 3).toString();
        String total = tableClientes.getTabla().getValueAt(fila, 4).toString();
        String dias = tableClientes.getTabla().getValueAt(fila, 5).toString();
        String estado = tableClientes.getTabla().getValueAt(fila, 6).toString();

        javax.swing.JFrame ventanaPadre = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        
        javax.swing.JPanel fondoOscuro = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                g.setColor(new java.awt.Color(0, 0, 0, 150));
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        fondoOscuro.setOpaque(false);
        fondoOscuro.addMouseListener(new java.awt.event.MouseAdapter() {});

        ventanaPadre.setGlassPane(fondoOscuro);
        fondoOscuro.setVisible(true);

        // ¡IMPORTANTE! Llamamos a RentasForm en lugar de ClientesForm
        RentasForm modal = new RentasForm(ventanaPadre, true); 
        
        // Enviamos los datos (asegúrate de que el orden coincida con el método en RentasForm)
        modal.cargarDatosEdicion(idClienteSeleccionado, cliente, vehiculo, fecha, dias, total, estado);
        
        modal.setLocationRelativeTo(ventanaPadre);
        modal.setVisible(true);

        fondoOscuro.setVisible(false);
    }//GEN-LAST:event_btnEditarAlquilerMouseClicked

    private void btnEliminarAlquilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarAlquilerMouseClicked
       if (idClienteSeleccionado == null) return;
        
        int fila = tableClientes.getTabla().getSelectedRow();
        if (fila == -1) return;

        // 1. Mostrar ventana de confirmación corregida para Alquileres
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "¿Está seguro que desea eliminar este alquiler del cliente " + tableClientes.getTabla().getValueAt(fila, 1).toString() + "?", 
            "Confirmar Eliminación", 
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE
        );

        // 2. Si el usuario presiona "Sí"
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            
            // AQUÍ IRÁ TU LÓGICA SQL
            System.out.println("Eliminando de la BD el alquiler ID: " + idClienteSeleccionado);
            
            // 3. Lo eliminamos visualmente de la tabla
            tableClientes.eliminarFila(fila);
            
            // 4. Como ya se eliminó, apagamos los botones de nuevo
            activarBotonesAccion(false);
        
        }
    }//GEN-LAST:event_btnEliminarAlquilerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private assets.PanelRound btnAgregarAlquiler;
    private assets.PanelRound btnEditarAlquiler;
    private assets.PanelRound btnEliminarAlquiler;
    private javax.swing.JLabel iconEditarAlquiler;
    private javax.swing.JLabel iconEliminarAlquiler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private assets.PanelRound panelRound1;
    public assets.TableRow tableClientes;
    private javax.swing.JLabel txtEditarAlquiler;
    private javax.swing.JLabel txtEliminarAlquiler;
    // End of variables declaration//GEN-END:variables
}
