/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.panels;
import DAO.DAO;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.ImageIcon;



/**
 *
 * @author PC
 */
public class VehiculosPanel extends javax.swing.JPanel {
        private String idVehiculoSeleccionado = null;
        private VehiculosForm vista;
        private VehiculosPanel vista2;
        private DAO dao;
        
    public VehiculosPanel() {
        initComponents();
        tableVehiculos.agregarFila(new Object[]{"1", "PBA-1234", "Sedán", "Toyota", "Corolla", "Activo", "Activo"});
        activarBotonesAccion(false);
        

    }
    // Método para activar o desactivar los botones dependiendo de si hay algo seleccionado
    private void activarBotonesAccion(boolean activar) {
        if (activar) {
            btnEditarVehiculo.setCursor(new Cursor(Cursor.HAND_CURSOR));
            btnEditarVehiculo.setBackground(new Color(254, 240, 228)); 
            txtEditarCliente.setForeground(new Color(251, 124, 20));
            iconEditarCliente.setIcon(new ImageIcon(getClass().getResource("/assets/iconPencilOrange.png")));
            btnEliminarVehiculos.setCursor(new Cursor(Cursor.HAND_CURSOR));
            btnEliminarVehiculos.setBackground(new Color(254, 234, 232));
            txtEliminarCliente.setForeground(new Color(255, 0, 51));
             iconEliminarCliente.setIcon(new ImageIcon(getClass().getResource("/assets/iconTrashRed.png")));
        } else {
           
            btnEditarVehiculo.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            btnEditarVehiculo.setBackground(new Color(245, 245, 245)); 
            txtEditarCliente.setForeground(new Color(170, 170, 170)); 
            iconEditarCliente.setIcon(new ImageIcon(getClass().getResource("/assets/iconPencilGray.png")));
            btnEliminarVehiculos.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            btnEliminarVehiculos.setBackground(new Color(245, 245, 245)); 
            txtEliminarCliente.setForeground(new Color(170, 170, 170)); 
            iconEliminarCliente.setIcon(new ImageIcon(getClass().getResource("/assets/iconTrashGray.png")));
            idVehiculoSeleccionado = null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new assets.PanelRound();
        tableVehiculos = new assets.TableRow();
        btnEditarVehiculo = new assets.PanelRound();
        iconEditarCliente = new javax.swing.JLabel();
        txtEditarCliente = new javax.swing.JLabel();
        btnAgregarVehiculo = new assets.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEliminarVehiculos = new assets.PanelRound();
        iconEliminarCliente = new javax.swing.JLabel();
        txtEliminarCliente = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(710, 502));

        panelRound1.setBackground(new java.awt.Color(253, 251, 250));
        panelRound1.setBorderColor(new java.awt.Color(204, 204, 204));
        panelRound1.setBorderSize(1);
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        tableVehiculos.setNombresColumnas("ID, Placa,Marca,Modelo,Tipo,Color,Estado");
        tableVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableVehiculosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnEditarVehiculo.setBackground(new java.awt.Color(254, 240, 228));
        btnEditarVehiculo.setRoundBottomLeft(20);
        btnEditarVehiculo.setRoundBottomRight(20);
        btnEditarVehiculo.setRoundTopLeft(20);
        btnEditarVehiculo.setRoundTopRight(20);
        btnEditarVehiculo.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnEditarVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarVehiculoMouseClicked(evt);
            }
        });

        iconEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconPencilOrange.png"))); // NOI18N

        txtEditarCliente.setBackground(new java.awt.Color(251, 124, 20));
        txtEditarCliente.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtEditarCliente.setForeground(new java.awt.Color(251, 124, 20));
        txtEditarCliente.setText("Editar");

        javax.swing.GroupLayout btnEditarVehiculoLayout = new javax.swing.GroupLayout(btnEditarVehiculo);
        btnEditarVehiculo.setLayout(btnEditarVehiculoLayout);
        btnEditarVehiculoLayout.setHorizontalGroup(
            btnEditarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditarVehiculoLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(iconEditarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnEditarVehiculoLayout.setVerticalGroup(
            btnEditarVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconEditarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
            .addComponent(txtEditarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnAgregarVehiculo.setBackground(new java.awt.Color(255, 153, 0));
        btnAgregarVehiculo.setRoundBottomLeft(20);
        btnAgregarVehiculo.setRoundBottomRight(20);
        btnAgregarVehiculo.setRoundTopLeft(20);
        btnAgregarVehiculo.setRoundTopRight(20);
        btnAgregarVehiculo.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnAgregarVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarVehiculoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarVehiculoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarVehiculoMouseExited(evt);
            }
        });
        btnAgregarVehiculo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("+");
        btnAgregarVehiculo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -32, 36, 90));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nuevo Vehiculo");
        btnAgregarVehiculo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 6, 150, -1));

        btnEliminarVehiculos.setBackground(new java.awt.Color(254, 234, 232));
        btnEliminarVehiculos.setRoundBottomLeft(20);
        btnEliminarVehiculos.setRoundBottomRight(20);
        btnEliminarVehiculos.setRoundTopLeft(20);
        btnEliminarVehiculos.setRoundTopRight(20);
        btnEliminarVehiculos.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnEliminarVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarVehiculosMouseClicked(evt);
            }
        });

        iconEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconTrashRed.png"))); // NOI18N

        txtEliminarCliente.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtEliminarCliente.setForeground(new java.awt.Color(255, 0, 51));
        txtEliminarCliente.setText("Eliminar");

        javax.swing.GroupLayout btnEliminarVehiculosLayout = new javax.swing.GroupLayout(btnEliminarVehiculos);
        btnEliminarVehiculos.setLayout(btnEliminarVehiculosLayout);
        btnEliminarVehiculosLayout.setHorizontalGroup(
            btnEliminarVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarVehiculosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconEliminarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEliminarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnEliminarVehiculosLayout.setVerticalGroup(
            btnEliminarVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarVehiculosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnEliminarVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconEliminarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(txtEliminarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnAgregarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarVehiculoMouseClicked

        javax.swing.JFrame ventanaPadre = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        
        // 2. Creamos el efecto de fondo oscuro
        javax.swing.JPanel fondoOscuro = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                g.setColor(new java.awt.Color(0, 0, 0, 150)); // Negro con transparencia
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        fondoOscuro.setOpaque(false);
        fondoOscuro.addMouseListener(new java.awt.event.MouseAdapter() {}); // Bloquea los clics de atrás

        //Encendemos el fondo oscuro
        ventanaPadre.setGlassPane(fondoOscuro);
        fondoOscuro.setVisible(true);

        VehiculosForm modal = new VehiculosForm(ventanaPadre, true); 
        modal.setLocationRelativeTo(ventanaPadre); // Lo centra en la pantalla
        
        modal.setVisible(true); // Abre la ventana (el código se pausa aquí hasta que cierres el modal)

        //SApagamos el fondo oscuro cuando se cierra el JDialog
        fondoOscuro.setVisible(false);
       
    }//GEN-LAST:event_btnAgregarVehiculoMouseClicked

    private void btnAgregarVehiculoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarVehiculoMouseEntered
        // TODO add your handling code here:
        btnAgregarVehiculo.setBackground(new Color(255,139,49));
    }//GEN-LAST:event_btnAgregarVehiculoMouseEntered

    private void btnAgregarVehiculoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarVehiculoMouseExited
        // TODO add your handling code here:
        btnAgregarVehiculo.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_btnAgregarVehiculoMouseExited

    private void tableVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVehiculosMouseClicked
     int filaSeleccionada = tableVehiculos.getTabla().getSelectedRow();

        if (filaSeleccionada != -1) {
            Object id = tableVehiculos.getTabla().getValueAt(filaSeleccionada, 0);
            
            if (id != null && !id.toString().trim().isEmpty()) {
                // Guardamos el ID del vehículo y encendemos los botones
                idVehiculoSeleccionado = id.toString();
                activarBotonesAccion(true);
            } else {
                activarBotonesAccion(false);
            }
        } else {
            // Si se deselecciona la fila
            activarBotonesAccion(false);
        }
    }//GEN-LAST:event_tableVehiculosMouseClicked

    private void btnEditarVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarVehiculoMouseClicked
        if (idVehiculoSeleccionado == null) return;

        int fila = tableVehiculos.getTabla().getSelectedRow();
        if (fila == -1) return; // Validación anti-crasheo

        // Extraer los datos de la fila seleccionada (columnas 1 al 6)
        String placa = tableVehiculos.getTabla().getValueAt(fila, 1).toString();
        String tipo = tableVehiculos.getTabla().getValueAt(fila, 2).toString();
        String marca = tableVehiculos.getTabla().getValueAt(fila, 3).toString();
        String modelo = tableVehiculos.getTabla().getValueAt(fila, 4).toString();
        String color = tableVehiculos.getTabla().getValueAt(fila, 5).toString();
        String estado = tableVehiculos.getTabla().getValueAt(fila, 6).toString();

        javax.swing.JFrame ventanaPadre = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        
        // Creamos el fondo oscuro
        javax.swing.JPanel fondoOscuro = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                g.setColor(new java.awt.Color(0, 0, 0, 150));
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        fondoOscuro.setOpaque(false);
        fondoOscuro.addMouseListener(new java.awt.event.MouseAdapter() {});

        ventanaPadre.setGlassPane(fondoOscuro);
        fondoOscuro.setVisible(true);

        // Abrimos el formulario de Vehículos
        VehiculosForm modal = new VehiculosForm(ventanaPadre, true); 
        
        // AQUÍ INYECTAMOS LOS DATOS
        modal.cargarDatosEdicion(idVehiculoSeleccionado, placa, tipo, marca, modelo, color, estado);
        
        modal.setLocationRelativeTo(ventanaPadre);
        modal.setVisible(true);

        fondoOscuro.setVisible(false);
    }//GEN-LAST:event_btnEditarVehiculoMouseClicked

    private void btnEliminarVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarVehiculosMouseClicked
     if (idVehiculoSeleccionado == null) return;
        
        int fila = tableVehiculos.getTabla().getSelectedRow();
        if (fila == -1) return; // Validación anti-crasheo

        // Ventana de confirmación
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "¿Está seguro que desea eliminar el vehículo con placa: " + tableVehiculos.getTabla().getValueAt(fila, 1).toString() + "?", 
            "Confirmar Eliminación", 
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE
        );

        // Si presiona "Sí"
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            
            // AQUÍ IRÁ TU LÓGICA SQL
            System.out.println("Eliminando vehículo ID: " + idVehiculoSeleccionado);
            
            // Lo eliminamos visualmente
            tableVehiculos.eliminarFila(fila);
            
            // Apagamos los botones porque la selección desapareció
            activarBotonesAccion(false);
        }
    }//GEN-LAST:event_btnEliminarVehiculosMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private assets.PanelRound btnAgregarVehiculo;
    private assets.PanelRound btnEditarVehiculo;
    private assets.PanelRound btnEliminarVehiculos;
    private javax.swing.JLabel iconEditarCliente;
    private javax.swing.JLabel iconEliminarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private assets.PanelRound panelRound1;
    public assets.TableRow tableVehiculos;
    private javax.swing.JLabel txtEditarCliente;
    private javax.swing.JLabel txtEliminarCliente;
    // End of variables declaration//GEN-END:variables
}
