/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.frames;
import Views.panels.ClientesPanel;
import java.awt.Color;
import javax.swing.ImageIcon;
import java.awt.Cursor;
import javax.swing.JPanel;
import Views.panels.InicioPanel;
import Views.panels.RentasPanel;
import Views.panels.VehiculosPanel;
import java.awt.BorderLayout;

/**
 *
 * @author PC
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    private boolean isInicioSelected = false;
    private boolean isClientesSelected = false;
    private boolean isVehiculosSelected = false;
    private boolean isRentasSelected = false;
    public Dashboard() {
        initComponents();
        isInicioSelected = true;
        
        // 2. Forzamos los colores activos (por si acaso)
        btnIncio.setBackground(new Color(253,239,222));
        iconInicio.setIcon(new ImageIcon(getClass().getResource("/assets/iconHomeOrange.png")));
        txtIncio.setForeground(new Color(251,124,20));
        showPanel(new InicioPanel());
    }
    private void resetearBotonesMenu() {
    isInicioSelected = false;
    isClientesSelected = false;
    
    btnIncio.setBackground(Color.WHITE);
    iconInicio.setIcon(new ImageIcon(getClass().getResource("/assets/iconHomeBlack.png")));
    txtIncio.setForeground(Color.BLACK);
    
    btnClientes.setBackground(Color.WHITE);
    iconClientes.setIcon(new ImageIcon(getClass().getResource("/assets/iconGroupBlack.png")));
    txtClientes.setForeground(Color.BLACK);
    
    btnVehiculos.setBackground(Color.WHITE);
    iconVehiculos.setIcon(new ImageIcon(getClass().getResource("/assets/iconCarBlack.png")));
    txtVehiculos.setForeground(Color.BLACK);
    
    btnRentas.setBackground(Color.WHITE);
    iconRentas.setIcon(new ImageIcon(getClass().getResource("/assets/iconRentaBlack.png")));
    txtRentas.setForeground(Color.BLACK);

}
    public void showPanel(JPanel panel){
    panel.setSize(contentInicio.getWidth(), contentInicio.getHeight());
    panel.setLocation(0,0);

    contentInicio.removeAll();
    contentInicio.setLayout(new BorderLayout());
    contentInicio.add(panel, BorderLayout.CENTER);

    contentInicio.revalidate();
    contentInicio.repaint();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoDashboard = new javax.swing.JPanel();
        fondoDashboard2 = new assets.PanelRound();
        panelTittle = new assets.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelTopBar = new assets.PanelRound();
        txtAdministrador = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtFecha = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        panelApartados = new assets.PanelRound();
        btnIncio = new assets.PanelRound();
        iconInicio = new javax.swing.JLabel();
        txtIncio = new javax.swing.JLabel();
        btnClientes = new assets.PanelRound();
        iconClientes = new javax.swing.JLabel();
        txtClientes = new javax.swing.JLabel();
        btnVehiculos = new assets.PanelRound();
        iconVehiculos = new javax.swing.JLabel();
        txtVehiculos = new javax.swing.JLabel();
        btnLogout = new assets.PanelRound();
        iconLogout = new javax.swing.JLabel();
        txtLogout = new javax.swing.JLabel();
        btnRentas = new assets.PanelRound();
        iconRentas = new javax.swing.JLabel();
        txtRentas = new javax.swing.JLabel();
        contentInicio = new assets.PanelRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoDashboard.setBackground(new java.awt.Color(252, 248, 243));
        fondoDashboard.setPreferredSize(new java.awt.Dimension(1020, 640));
        fondoDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoDashboard2.setBackground(new java.awt.Color(204, 204, 255));
        fondoDashboard2.setPreferredSize(new java.awt.Dimension(980, 600));
        fondoDashboard2.setRoundBottomLeft(40);
        fondoDashboard2.setRoundBottomRight(40);
        fondoDashboard2.setRoundTopLeft(40);
        fondoDashboard2.setRoundTopRight(40);
        fondoDashboard2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTittle.setBackground(new java.awt.Color(255, 255, 255));
        panelTittle.setRoundTopLeft(40);
        panelTittle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(233, 127, 45));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconCarPrincipalOrange.png"))); // NOI18N
        panelTittle.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, -1, 69));

        jLabel3.setFont(new java.awt.Font("Roboto SemiCondensed Medium", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(108, 77, 59));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RENTA");
        panelTittle.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 16, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto SemiCondensed Medium", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(233, 127, 45));
        jLabel4.setText("CAR");
        panelTittle.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 16, 110, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(85, 51, 35));
        jLabel7.setText("Sistema de Gestión");
        panelTittle.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 51, 130, -1));
        panelTittle.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 270, 10));

        fondoDashboard2.add(panelTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, -1));

        panelTopBar.setBackground(new java.awt.Color(255, 255, 255));
        panelTopBar.setRoundTopRight(40);
        panelTopBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAdministrador.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        txtAdministrador.setText("Admin");
        panelTopBar.add(txtAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 150, 80));
        panelTopBar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 290, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/userRoundOrange.png"))); // NOI18N
        panelTopBar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, 80));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelTopBar.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 10, 40));

        txtFecha.setFont(new java.awt.Font("Roboto SemiBold", 1, 18)); // NOI18N
        txtFecha.setText("Viernes 24 de Junio del 2026");
        panelTopBar.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 22, 260, 40));
        panelTopBar.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 80, 770, 10));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelTopBar.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 10, 80));

        fondoDashboard2.add(panelTopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 720, 90));

        panelApartados.setBackground(new java.awt.Color(255, 255, 255));
        panelApartados.setRoundBottomLeft(40);
        panelApartados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIncio.setBackground(new java.awt.Color(255, 255, 255));
        btnIncio.setRoundBottomLeft(20);
        btnIncio.setRoundBottomRight(20);
        btnIncio.setRoundTopLeft(20);
        btnIncio.setRoundTopRight(20);
        btnIncio.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnIncio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIncioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIncioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIncioMouseExited(evt);
            }
        });
        btnIncio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconHomeBlack.png"))); // NOI18N
        btnIncio.add(iconInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 33, 49));

        txtIncio.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        txtIncio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtIncio.setText("Inicio");
        btnIncio.add(txtIncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, -1, 250, 50));

        panelApartados.add(btnIncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, -1, -1));

        btnClientes.setBackground(new java.awt.Color(255, 255, 255));
        btnClientes.setRoundBottomLeft(20);
        btnClientes.setRoundBottomRight(20);
        btnClientes.setRoundTopLeft(20);
        btnClientes.setRoundTopRight(20);
        btnClientes.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClientesMouseExited(evt);
            }
        });
        btnClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconGroupBlack.png"))); // NOI18N
        btnClientes.add(iconClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 33, 49));

        txtClientes.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        txtClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtClientes.setText("Clientes");
        btnClientes.add(txtClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, -1, 250, 50));

        panelApartados.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 83, -1, 50));

        btnVehiculos.setBackground(new java.awt.Color(255, 255, 255));
        btnVehiculos.setRoundBottomLeft(20);
        btnVehiculos.setRoundBottomRight(20);
        btnVehiculos.setRoundTopLeft(20);
        btnVehiculos.setRoundTopRight(20);
        btnVehiculos.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVehiculosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVehiculosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVehiculosMouseExited(evt);
            }
        });
        btnVehiculos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconCarBlack.png"))); // NOI18N
        btnVehiculos.add(iconVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 33, 49));

        txtVehiculos.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        txtVehiculos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtVehiculos.setText("Vehiculos");
        btnVehiculos.add(txtVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, -1, 250, 50));

        panelApartados.add(btnVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 150, -1, 50));

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setRoundBottomLeft(20);
        btnLogout.setRoundBottomRight(20);
        btnLogout.setRoundTopLeft(20);
        btnLogout.setRoundTopRight(20);
        btnLogout.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        btnLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconLogoutBlack.png"))); // NOI18N
        btnLogout.add(iconLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 33, 49));

        txtLogout.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        txtLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLogout.setText("Cerrar Sesion");
        btnLogout.add(txtLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 50));

        panelApartados.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 424, 250, -1));

        btnRentas.setBackground(new java.awt.Color(255, 255, 255));
        btnRentas.setRoundBottomLeft(20);
        btnRentas.setRoundBottomRight(20);
        btnRentas.setRoundTopLeft(20);
        btnRentas.setRoundTopRight(20);
        btnRentas.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnRentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRentasMouseExited(evt);
            }
        });
        btnRentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconRentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconRentaBlack.png"))); // NOI18N
        btnRentas.add(iconRentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 33, 49));

        txtRentas.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        txtRentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRentas.setText("Rentas");
        btnRentas.add(txtRentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, -1, 250, 50));

        panelApartados.add(btnRentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 217, -1, 50));

        fondoDashboard2.add(panelApartados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 270, 500));

        contentInicio.setRequestFocusEnabled(false);
        contentInicio.setRoundBottomRight(40);
        contentInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        fondoDashboard2.add(contentInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 710, 490));

        fondoDashboard.add(fondoDashboard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 1004, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseExited
        // TODO add your handling code here:
        if (!isClientesSelected) {
            btnClientes.setBackground(Color.white);
            iconClientes.setIcon(new ImageIcon(getClass().getResource("/assets/iconGroupBlack.png")));
            txtClientes.setForeground(Color.black);
        }
    }//GEN-LAST:event_btnClientesMouseExited

    private void btnClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseEntered
        // TODO add your handling code here:
        if (!isClientesSelected) {
            btnClientes.setBackground(new Color(253,239,222));
            iconClientes.setIcon(new ImageIcon(getClass().getResource("/assets/iconGroupOrange.png")));
            txtClientes.setForeground(new Color(251,124,20));
        }
    }//GEN-LAST:event_btnClientesMouseEntered

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
        // TODO add your handling code here:
        resetearBotonesMenu();
        isClientesSelected = true;

        btnClientes.setBackground(new Color(253,239,222));
        iconClientes.setIcon(new ImageIcon(getClass().getResource("/assets/iconGroupOrange.png")));
        txtClientes.setForeground(new Color(251,124,20));
        showPanel(new ClientesPanel());
    }//GEN-LAST:event_btnClientesMouseClicked

    private void btnIncioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIncioMouseExited
        if (!isInicioSelected) {
            btnIncio.setBackground(Color.white);
            iconInicio.setIcon(new ImageIcon(getClass().getResource("/assets/iconHomeBlack.png")));
            txtIncio.setForeground(Color.black);
        }
    }//GEN-LAST:event_btnIncioMouseExited

    private void btnIncioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIncioMouseEntered
        // TODO add your handling code here:
        if (!isInicioSelected) {
            btnIncio.setBackground(new Color(253,239,222));
            iconInicio.setIcon(new ImageIcon(getClass().getResource("/assets/iconHomeOrange.png")));
            txtIncio.setForeground(new Color(251,124,20));
        }
    }//GEN-LAST:event_btnIncioMouseEntered

    private void btnIncioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIncioMouseClicked
        showPanel(new InicioPanel());
        resetearBotonesMenu();
        isInicioSelected = true;

        btnIncio.setBackground(new Color(253,239,222));
        iconInicio.setIcon(new ImageIcon(getClass().getResource("/assets/iconHomeOrange.png")));
        txtIncio.setForeground(new Color(251,124,20));
        showPanel(new InicioPanel());
    }//GEN-LAST:event_btnIncioMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        Login login = new Login();
        login .setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        btnLogout.setBackground(new Color(253,239,222));
        iconLogout.setIcon(new ImageIcon(getClass().getResource("/assets/iconLogoutOrange.png")));
        txtLogout.setForeground(new Color(251,124,20));
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        btnLogout.setBackground(Color.white);
        iconLogout.setIcon(new ImageIcon(getClass().getResource("/assets/iconLogoutBlack.png")));
        txtLogout.setForeground(Color.black);
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculosMouseClicked
        // TODO add your handling code here:
        resetearBotonesMenu();
        isVehiculosSelected = true;

        btnVehiculos.setBackground(new Color(253,239,222));
        iconVehiculos.setIcon(new ImageIcon(getClass().getResource("/assets/iconCarOrange.png")));
        txtVehiculos.setForeground(new Color(251,124,20));
        showPanel(new VehiculosPanel());
        
    }//GEN-LAST:event_btnVehiculosMouseClicked

    private void btnVehiculosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculosMouseEntered
        // TODO add your handling code here:
         if (!isVehiculosSelected) {
            btnVehiculos.setBackground(new Color(253,239,222));
            iconVehiculos.setIcon(new ImageIcon(getClass().getResource("/assets/iconCarOrange.png")));
            txtVehiculos.setForeground(new Color(251,124,20));
        }
    }//GEN-LAST:event_btnVehiculosMouseEntered

    private void btnVehiculosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculosMouseExited
        // TODO add your handling code here:
         if (!isVehiculosSelected) {
            btnVehiculos.setBackground(Color.white);
            iconVehiculos.setIcon(new ImageIcon(getClass().getResource("/assets/iconCarBlack.png")));
            txtVehiculos.setForeground(Color.black);
        }
    }//GEN-LAST:event_btnVehiculosMouseExited

    private void btnRentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRentasMouseClicked
        // TODO add your handling code here:
        resetearBotonesMenu();
        isRentasSelected = true;

        btnRentas.setBackground(new Color(253,239,222));
        iconRentas.setIcon(new ImageIcon(getClass().getResource("/assets/iconRentaOrange.png")));
        txtRentas.setForeground(new Color(251,124,20));
        showPanel(new RentasPanel());
    }//GEN-LAST:event_btnRentasMouseClicked

    private void btnRentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRentasMouseEntered
        // TODO add your handling code here:
        if (!isRentasSelected) {
            btnRentas.setBackground(new Color(253,239,222));
            iconRentas.setIcon(new ImageIcon(getClass().getResource("/assets/iconRentaOrange.png")));
            txtRentas.setForeground(new Color(251,124,20));
        }
    }//GEN-LAST:event_btnRentasMouseEntered

    private void btnRentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRentasMouseExited
        // TODO add your handling code here:
         if (!isRentasSelected) {
            btnRentas.setBackground(Color.white);
            iconRentas.setIcon(new ImageIcon(getClass().getResource("/assets/iconRentaBlack.png")));
            txtRentas.setForeground(Color.black);
        }
    }//GEN-LAST:event_btnRentasMouseExited
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private assets.PanelRound btnClientes;
    private assets.PanelRound btnIncio;
    private assets.PanelRound btnLogout;
    private assets.PanelRound btnRentas;
    private assets.PanelRound btnVehiculos;
    private assets.PanelRound contentInicio;
    private javax.swing.JPanel fondoDashboard;
    private assets.PanelRound fondoDashboard2;
    private javax.swing.JLabel iconClientes;
    private javax.swing.JLabel iconInicio;
    private javax.swing.JLabel iconLogout;
    private javax.swing.JLabel iconRentas;
    private javax.swing.JLabel iconVehiculos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private assets.PanelRound panelApartados;
    private assets.PanelRound panelTittle;
    private assets.PanelRound panelTopBar;
    private javax.swing.JLabel txtAdministrador;
    private javax.swing.JLabel txtClientes;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JLabel txtIncio;
    private javax.swing.JLabel txtLogout;
    private javax.swing.JLabel txtRentas;
    private javax.swing.JLabel txtVehiculos;
    // End of variables declaration//GEN-END:variables
}
