/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.frames;
import Views.frames.Dashboard;
import java.awt.Color;
import java.awt.Cursor;

/**
 *
 * @author PC
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setFocusable(true);
        this.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnIniciarSesion = new assets.PanelRound();
        lbIniciarSesion = new javax.swing.JLabel();
        panelUsuario = new assets.PanelRound();
        jLabel8 = new javax.swing.JLabel();
        flUsuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        panelContraseña = new assets.PanelRound();
        jLabel9 = new javax.swing.JLabel();
        flContraseña = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogin.setBackground(new java.awt.Color(255, 255, 255));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(233, 127, 45));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconCarPrincipalOrange.png"))); // NOI18N
        panelLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 35, -1, 69));

        jLabel3.setFont(new java.awt.Font("Roboto SemiCondensed Medium", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(108, 77, 59));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RENTA");
        panelLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 35, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto SemiCondensed Medium", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(233, 127, 45));
        jLabel4.setText("CAR");
        panelLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 35, 110, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(85, 51, 35));
        jLabel5.setText("Inicia Sesion Para Continuar");
        panelLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 190, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(85, 54, 35));
        jLabel6.setText("¡BIENVENIDO!");
        panelLogin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 140, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(85, 51, 35));
        jLabel7.setText("Sistema de Gestión");
        panelLogin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 130, -1));

        btnIniciarSesion.setBackground(new java.awt.Color(233, 127, 45));
        btnIniciarSesion.setRoundBottomLeft(50);
        btnIniciarSesion.setRoundBottomRight(50);
        btnIniciarSesion.setRoundTopLeft(50);
        btnIniciarSesion.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnIniciarSesion.setRoundTopRight(50);
        btnIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseExited(evt);
            }
        });
        btnIniciarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIniciarSesion.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        lbIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lbIniciarSesion.setText("Inciar Sesión");
        btnIniciarSesion.add(lbIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        panelLogin.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 200, 50));

        panelUsuario.setBackground(new java.awt.Color(255, 255, 255));
        panelUsuario.setRoundBottomLeft(30);
        panelUsuario.setRoundBottomRight(30);
        panelUsuario.setRoundTopLeft(30);
        panelUsuario.setRoundTopRight(30);
        panelUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconUserOrange.png"))); // NOI18N
        panelUsuario.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 37, -1));

        flUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        flUsuario.setForeground(new java.awt.Color(204, 204, 204));
        flUsuario.setText("Ingrese su Usuario");
        flUsuario.setBorder(null);
        flUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                flUsuarioMousePressed(evt);
            }
        });
        flUsuario.addActionListener(this::flUsuarioActionPerformed);
        panelUsuario.add(flUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 200, 40));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setPreferredSize(new java.awt.Dimension(100, 120));
        panelUsuario.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 10));

        panelLogin.add(panelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 270, 60));

        panelContraseña.setBackground(new java.awt.Color(255, 255, 255));
        panelContraseña.setRoundBottomLeft(30);
        panelContraseña.setRoundBottomRight(30);
        panelContraseña.setRoundTopLeft(30);
        panelContraseña.setRoundTopRight(30);
        panelContraseña.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconLockOrange.png"))); // NOI18N
        panelContraseña.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        flContraseña.setForeground(new java.awt.Color(204, 204, 204));
        flContraseña.setText("********");
        flContraseña.setBorder(null);
        flContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                flContraseñaMousePressed(evt);
            }
        });
        flContraseña.addActionListener(this::flContraseñaActionPerformed);
        panelContraseña.add(flContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 210, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setPreferredSize(new java.awt.Dimension(150, 100));
        panelContraseña.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 10));

        panelLogin.add(panelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 270, 60));

        fondo.add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 340, 3648));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bgLogin1.png"))); // NOI18N
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseEntered
        // TODO add your handling code here:
        btnIniciarSesion.setBackground(new Color(255,139,49));
    }//GEN-LAST:event_btnIniciarSesionMouseEntered

    private void btnIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseExited
        // TODO add your handling code here:
        btnIniciarSesion.setBackground(new Color(233,127,45));
    }//GEN-LAST:event_btnIniciarSesionMouseExited

    private void flUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flUsuarioMousePressed
        // TODO add your handling code here:
        if(flUsuario.getText().equals("Ingrese su Usuario")){
            flUsuario.setText("");
            flUsuario.setForeground(Color.black);
        }
        if(String.valueOf(flContraseña.getPassword()).isEmpty()){
            flContraseña.setText("********");
            flContraseña.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_flUsuarioMousePressed

    private void flContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flContraseñaActionPerformed

    private void flContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flContraseñaMousePressed
        // TODO add your handling code here:
        if(String.valueOf(flContraseña.getPassword()).equals("********")){
            flContraseña.setText("");
            flContraseña.setForeground(Color.black);
            
        }
        if(flUsuario.getText().isEmpty()){
        
            flUsuario.setText("Ingrese su Usuario");
            flUsuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_flContraseñaMousePressed

    private void flUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flUsuarioActionPerformed

    private void btnIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseClicked
        // TODO add your handling code here:
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIniciarSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private assets.PanelRound btnIniciarSesion;
    private javax.swing.JPasswordField flContraseña;
    private javax.swing.JTextField flUsuario;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbIniciarSesion;
    private assets.PanelRound panelContraseña;
    private javax.swing.JPanel panelLogin;
    private assets.PanelRound panelUsuario;
    // End of variables declaration//GEN-END:variables
}
